#!/bin/bash

echo "Doom Speedrun Helper - by Mark Ridlen"

# This first part will help you configure doom-speedrun-helper
DOOM_SR_CONFIG=~/.doom-speedrun-helper
if [ ! -f "$DOOM_SR_CONFIG" ]; then
	echo "No configuration file found... starting manual configuration..."

	echo "Finding Ultimate Doom wad..."
	DOOMU_WAD=$(find ~ -name "doomu.wad" | head -n1)
	if [ -z "$DOOMU_WAD" ]; then
		DOOMU_ENABLED=0
	else
		DOOMU_ENABLED=1
	fi
	
	echo "Finding Doom 2 wad..."
	DOOM2_WAD=$(find ~ -name "doom2.wad" | head -n1)
	if [ -z "$DOOM2_WAD" ]; then
		DOOM2_ENABLED=0
	else
		DOOM2_ENABLED=1
	fi

	echo "Finding GZDoom..."
	GZDOOM_PATH=$(find ~ -type f -name "gzdoom")
	if [ -z "$GZDOOM_PATH" ]; then
		GZDOOM_ENABLED=0
	else
		GZDOOM_ENABLED=1
	fi

	echo "Finding prboom..."
	PRBOOM_PATH=$(which prboom | grep -v "no prboom")
	if [ -z "$PRBOOM_PATH" ]; then
		PRBOOM_ENABLED=0
	else
		PRBOOM_ENABLED=1
	fi

	echo "Finding prboom-plus..."
	PRBOOM_PLUS_PATH=$(which prboom | grep -v "no prboom")
	if [ -z "$PRBOOM_PATH" ]; then
		PRBOOM_PLUS_ENABLED=0
	else
		PRBOOM_PLUS_ENABLED=1
	fi

	#echo "[TBD] Finding crispy..."

	#Dump all variables to configuration file
	touch ~/.doom-speedrun-helper
	echo "DOOMU_WAD=$DOOMU_WAD" >> ~/.doom-speedrun-helper
	echo "DOOM2_WAD=$DOOM2_WAD" >> ~/.doom-speedrun-helper
	echo "DOOMU_ENABLED=$DOOMU_ENABLED" >> ~/.doom-speedrun-helper
	echo "DOOM2_ENABLED=$DOOM2_ENABLED" >> ~/.doom-speedrun-helper
	echo "GZDOOM_PATH=$GZDOOM_PATH" >> ~/.doom-speedrun-helper
	echo "GZDOOM_ENABLED=$GZDOOM_ENABLED" >> ~/.doom-speedrun-helper
	echo "PRBOOM_PATH=$PRBOOM_PATH" >> ~/.doom-speedrun-helper
	echo "PRBOOM_ENABLED=$PRBOOM_ENABLED" >> ~/.doom-speedrun-helper
	echo "PRBOOM_PLUS_PATH=$PRBOOM_PLUS_PATH" >> ~/.doom-speedrun-helper
	echo "PRBOOM_PLUS_ENABLED=$PRBOOM_PLUS_ENABLED" >> ~/.doom-speedrun-helper

	echo " "
	echo "Configuration file written: ~/.doom-speedrun-helper"
	cat ~/.doom-speedrun-helper
fi

run_doom() {
	echo "Loading vars from file ${filelist[$selection]}..."
	source ${filelist[$selection]}
	source $DOOM_SR_CONFIG
	DEMO_DIR="demos/$(echo "${filelist[$selection]}" | awk -F "/" '{ print $2 }')"
	mkdir -p $DEMO_DIR
	echo "NAME: $NAME, IWAD: $IWAD, SKILL: $SKILL, STARTING_LEVEL: $STARTING_LEVEL"
	if [[ "$IWAD" == "DOOMU" ]]; then
		SELECTED_IWAD=$DOOMU_WAD
	fi
	echo "SELECTED_IWAD = $SELECTED_IWAD"
	read -n1 -r -p "Press space to continue..." key

	if [ "$key" = '' ]; then
		prboom-plus -config ~/prboom-plus.cfg -iwad $SELECTED_IWAD -warp $STARTING_LEVEL -skill $SKILL -record $DEMO_DIR/$IWAD-$SKILL-$(date +%m"-"%d"-"%Y"_"%H"-"%M"-"%S).lmp
	fi
}

play_existing_category() {
	echo "Playing Existing Speedrun Category"
	
	i=0
	for f in category/*
	do
		filelist[ $i ]=$f
		printf "$i) "
		cat $f | grep "NAME" | awk -F "=" '{ print $2 }'
		(( i++ ))
	done

	#echo "file list length = ${#filelist[@]}"

	read -p "> " selection

	run_doom
}

create_new_category() {
	echo "Creating New Speedrun Category"
	echo "Skill:"
	echo "0) No Monsters"
	echo "1) I'm Too Young To Die"
	echo "2) Hey Not Too Rough"
	echo "3) Hurt Me Plenty"
	echo "4) Ultraviolence"
	echo "5) Nightmare!"

	echo " "

	echo "Which Doom IWAD?"
	echo "1) Ultimate Doom"
	echo "2) Doom 2"

	echo " "

	echo "Starting Level? (Doom e.g.: '1 1' Doom 2 e.g.: '21')"

	echo " "
}

render_demo_video() {
	echo "Rendering Demo Video"
}
if [ -f "$DOOM_SR_CONFIG" ]; then
	#This second part is a menu for configuring your speedrun

	echo "==================================="
	echo "=Welcome to DOOM Speedrun Helper! ="
	echo "==================================="
	echo " "
	echo "What would you like to do?"
	echo "1) Create New Category"
	echo "2) Play Existing Category"
	echo "3) Render Demo Video"
	echo "4) Exit"

	while :
	do
    		cat<<EOF
    		=================================
    		Welcome to DOOM Speedrun Helper
    		---------------------------------
    		Please enter your choice:

    		1) Play Existing Speedrun Category
		2) Create New Speedrun Category
		3) Render Demo Video
		Q) Exit
    		---------------------------------
EOF
    		read -n1 -s
    		case "$REPLY" in
    			"1")  play_existing_category    ;;
    			"2")  create_new_category       ;;
    			"3")  render_demo_video         ;;
    			"Q")  exit                      ;;
    			"q")  exit                      ;; 
     			* )  echo "invalid option"     ;;
    		esac
done
fi
